<?php /** @var \RLTSquare\BestSeller\Block\Product\GridProduct $block */ ?>
<?php if ($block->isEnableDisable() && $block->getCurrentPagePath()): ?>
    <?php $collection = $block->getCollection();
    $list_product = $block->getListProduct();
    $iterator = 1;
    $image = 'category_page_grid';
    $pos = $list_product->getPositioned();
    $_helper = $block->getCatalogHelper();
    $config = $list_product->getWidgetCfg();
    $showCart = 1;
    $showCompare = 0;
    $showWishlist = 1;
    $showReview = 1;
    $viewMode = 'grid';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>
    <?php if ($collection->getData()): ?>
        <!-- products wrapper most_viewed-wrapper custom_grid-wrapper content-products -->
        <div class="">
            <?php $iterator = 1; ?>
            <div class="title__h1">
                <h1><?= __('Best sellers') ?></h1>
            </div>
            <!-- products list items product-items  -->
            <ol class="products list items product-items regulars slider">
                <?php foreach ($collection->getData() as $data) { ?>
                    <?php $product_id = $data['product_id']; ?>
                    <?php $_product = $block->getLoadProduct($product_id); ?>
                    <?php if (isset($_product)): ?>
                        <?php if ($_product->getID()): ?>
                            <?php /* @escapeNotVerified */ ?>
                            <?php echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item ">' ?>
                            <div data-container="product-grid">
                                    <?php $productImage = $list_product->getImage($_product, $image); ?>
                                    <?php if ($pos != null): ?>
                                        <?php $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"'; ?>
                                    <?php endif; ?>
                                    <div>
                                        <?php $_productNameStripped = $list_product->stripTags($_product->getName(), null, true); ?>
                                        <div class="product-hover">
                                            <a href="<?php /* @escapeNotVerified */
                                            echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                            tabindex="-1">
                                                <?php echo $block->getLazyLoadedImage($productImage) ?>
                                            </a>
                                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                                <div class="hover-box clearfix">
                                                    <div class="product actions clearfix">
                                                        <?php if ($showCart): ?>
                                                            <div class="actions-primary actions-cart alotheme-tooltip">
                                                                <?php if ($_product->isSaleable()): ?>
                                                                    <?php $postParams = $list_product->getAddToCartPostParams($_product); ?>

                                                                    <div class="product details product-item-details products-textlink clearfix">
                                                                            <p>More colours available</p>
                                                                            <h4 class="product-name product-item-name">
                                                                                <a class="product-item-link"
                                                                                href="<?php /* @escapeNotVerified */
                                                                                echo $_product->getProductUrl() ?>"
                                                                                title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                                                                    <?php /* @escapeNotVerified */
                                                                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                                                                </a>
                                                                            </h4>
                                                                        <?php echo $list_product->getProductPrice($_product) ?>
                                                                        <?php echo $showReview ? $list_product->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                                                                    </div>

                                                                    <form data-role="tocart-form"
                                                                        action="<?php echo $postParams['action']; ?>"
                                                                        method="post">
                                                                        <input type="hidden" name="product"
                                                                            value="<?php echo $postParams['data']['product']; ?>">
                                                                        <input type="hidden"
                                                                            name="<?php echo \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                            value="<?php echo $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                                        <?php echo $list_product->getBlockHtml('formkey') ?>
                                                                        <button type="submit"
                                                                            title="<?php echo $list_product->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="bottom__standard">
                                                                                <span class="tooltip"><?php echo __('Add to Cart') ?>
                                                                                </span>
                                                                        </button>
                                                                    </form>
                                                                    <?php else: ?>
                                                                        <?php if ($_product->getIsSalable()): ?>
                                                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                                    echo __('In stock') ?></span></div>
                                                                        <?php else: ?>
                                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                                    echo __('Out of stock') ?></span></div>
                                                                        <?php endif; ?>
                                                                <?php endif; ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        
                                    </div>
                                </div>
                            <?php echo ($iterator == count($collection) + 1) ? '</li>' : '' ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php } ?>
            </ol>
        </div>

        <div class="">
            <?php $iterator = 1; ?>
            <div class="title__h1">
                <h1><?= __('New arrivals') ?></h1>
            </div>
            <!-- products list items product-items  -->
            <ol class="products list items product-items regulars slider">
                <?php foreach ($collection->getData() as $data) { ?>
                    <?php $product_id = $data['product_id']; ?>
                    <?php $_product = $block->getLoadProduct($product_id); ?>
                    <?php if (isset($_product)): ?>
                        <?php if ($_product->getID()): ?>
                            <?php /* @escapeNotVerified */ ?>
                            <?php echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item ">' ?>
                            <div data-container="product-grid">
                                    <?php $productImage = $list_product->getImage($_product, $image); ?>
                                    <?php if ($pos != null): ?>
                                        <?php $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"'; ?>
                                    <?php endif; ?>
                                    <div>
                                        <?php $_productNameStripped = $list_product->stripTags($_product->getName(), null, true); ?>
                                        <div class="product-hover">
                                            <a href="<?php /* @escapeNotVerified */
                                            echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                            tabindex="-1">
                                                <?php echo $block->getLazyLoadedImage($productImage) ?>
                                            </a>
                                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                                <div class="hover-box clearfix">
                                                    <div class="product actions clearfix">
                                                        <?php if ($showCart): ?>
                                                            <div class="actions-primary actions-cart alotheme-tooltip">
                                                                <?php if ($_product->isSaleable()): ?>
                                                                    <?php $postParams = $list_product->getAddToCartPostParams($_product); ?>

                                                                    <div class="product details product-item-details products-textlink clearfix">
                                                                            <p>More colours available</p>
                                                                            <h4 class="product-name product-item-name">
                                                                                <a class="product-item-link"
                                                                                href="<?php /* @escapeNotVerified */
                                                                                echo $_product->getProductUrl() ?>"
                                                                                title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                                                                    <?php /* @escapeNotVerified */
                                                                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                                                                </a>
                                                                            </h4>
                                                                        <?php echo $list_product->getProductPrice($_product) ?>
                                                                        <?php echo $showReview ? $list_product->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
                                                                    </div>

                                                                    <form data-role="tocart-form"
                                                                        action="<?php echo $postParams['action']; ?>"
                                                                        method="post">
                                                                        <input type="hidden" name="product"
                                                                            value="<?php echo $postParams['data']['product']; ?>">
                                                                        <input type="hidden"
                                                                            name="<?php echo \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED; ?>"
                                                                            value="<?php echo $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                                        <?php echo $list_product->getBlockHtml('formkey') ?>
                                                                        <button type="submit"
                                                                            title="<?php echo $list_product->escapeHtml(__('Add to Cart')); ?>"
                                                                            class="bottom__standard">
                                                                                <span class="tooltip"><?php echo __('Add to Cart') ?>
                                                                                </span>
                                                                        </button>
                                                                    </form>
                                                                    <?php else: ?>
                                                                        <?php if ($_product->getIsSalable()): ?>
                                                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                                    echo __('In stock') ?></span></div>
                                                                        <?php else: ?>
                                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                                    echo __('Out of stock') ?></span></div>
                                                                        <?php endif; ?>
                                                                <?php endif; ?>
                                                            </div>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        
                                    </div>
                                </div>
                            <?php echo ($iterator == count($collection) + 1) ? '</li>' : '' ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php } ?>
            </ol>
        </div>
    <?php endif; ?>

    <script>
        // define is used to register a module in require js
        require(['jquery', 'slick'], function ($) {
            //your js code here
            jQuery(function () {
                $(".regulars").slick({
                dot: true,
	            infinite: true,
	            slidesToShow: 4,
                slidesToScroll: 4,
                arrows: true,
                swipeToSlide: true,
                responsive: [
                    {
                    breakpoint: 480,
                    settings: {
                        arrows: false,
                        centerMode: true,
                        centerPadding: '40px',
                        slidesToShow: 1
                        }
                    },
                    {
                    breakpoint: 768,
                    settings: {
                        arrows: false,
                        centerMode: true,
                        centerPadding: '40px',
                        slidesToShow: 3
                        }
                    },
                    {
                    breakpoint: 1024,
                    settings: {
                        arrows: false,
                        centerMode: true,
                        centerPadding: '40px',
                        slidesToShow: 3,
                        arrows: true,
                        }
                    }
                ]
	        });
            });
        });
    </script>
<?php endif; ?>
